package ar.unlam.edu.pb2;

public enum Pais {
	ARGENTINA, BRASIL, COLOMBIA, ESPAÑA, ALEMANIA, 
	PORTUGAL, URUGUAY, ITALIA, QATAR, INGLATERRA, 
	HOLANDA, EEUU, ECUADOR, IRAN, GALES, FRANCIA, 
	AUSTRALIA, DINAMARCIA, TUNEZ, COSTA_RICA;
}
